openapi: 3.0.3
info:
  title: E-Loket KDG - Organigram External API
  description: API voor beheer van functies, taken en organigram in het E-Loket KDG.
  version: "1.0.0"
servers:
  - url: https://api.kdg.be/api/OrganigramExternal
paths:
  /organigramFuncties:
    get:
      summary: Haal de lijst van functies op
      responses:
        '200':
          description: Lijst van functies
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Functie'
    post:
      summary: Voeg een nieuwe functie toe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Functie'
      responses:
        '201':
          description: Functie succesvol toegevoegd

  /organigramFuncties/{functieId}/taak:
    put:
      summary: Voeg een taak toe aan een functie
      parameters:
        - in: path
          name: functieId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                taakId:
                  type: integer
      responses:
        '200':
          description: Taak toegevoegd aan functie

  /organigramFuncties/{functieId}:
    put:
      summary: Wijzig een functienaam
      parameters:
        - in: path
          name: functieId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                titel:
                  type: string
      responses:
        '200':
          description: Functie gewijzigd
    delete:
      summary: Verwijder een functie
      parameters:
        - in: path
          name: functieId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Functie verwijderd

  /organigramTaken:
    get:
      summary: Haal de lijst van taken op
      responses:
        '200':
          description: Lijst van taken
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Taak'
    post:
      summary: Voeg een nieuwe taak toe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Taak'
      responses:
        '201':
          description: Taak toegevoegd

  /organigramTaken/{taakId}:
    put:
      summary: Wijzig een taak of activeer/deactiveer een taak
      parameters:
        - in: path
          name: taakId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                taak:
                  type: string
                actief:
                  type: boolean
      responses:
        '200':
          description: Taak gewijzigd
    delete:
      summary: Verwijder een taak
      parameters:
        - in: path
          name: taakId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Taak verwijderd

  /organigram:
    get:
      summary: Haal het volledige organigram op
      responses:
        '200':
          description: Lijst van nodes en medewerkers
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/OrganigramNode'

  /organigram:
    post:
      summary: Voeg een nieuwe node toe aan het organigram
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganigramNode'
      responses:
        '201':
          description: Node toegevoegd

  /organigram/{nodeId}:
    put:
      summary: Wijzig een node in het organigram
      parameters:
        - in: path
          name: nodeId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrganigramNode'
      responses:
        '200':
          description: Node gewijzigd
    delete:
      summary: Verwijder een node uit het organigram
      parameters:
        - in: path
          name: nodeId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Node verwijderd

components:
  schemas:
    Functie:
      type: object
      properties:
        id:
          type: integer
        titel:
          type: string
        toegewezenTaken:
          type: array
          items:
            type: string

    Taak:
      type: object
      properties:
        id:
          type: integer
        taak:
          type: string
        actief:
          type: boolean

    OrganigramNode:
      type: object
      properties:
        lidId:
          type: integer
        parentNodeId:
          type: integer
        gebruikerId:
          type: integer
        name:
          type: string
        compositeId:
          type: string
        compositeParentId:
          type: string
        nodeType:
          type: integer
        toegewezenFuncties:
          type: array
          items:
            type: string
        isHoofdVerdeling:
          type: boolean
        parentNodeNaam:
          type: string
        lidNodeId:
          type: integer
